use EOF

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,10 +34,16 @@ jobs:
         ssh -o StrictHostKeyChecking=no \
           -o UserKnownHostsFile=/home/runner/.ssh/known_hosts \
           -i ec2sshkeypair.pem \
-          ec2-user@18.144.54.243 \
-          if docker ps -q; then \
-            docker kill  $(docker ps -q) || true; \
-          fi; \
-          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io && \
-          docker pull ghcr.io/peakaltitudestudio/pas-website-ghrc:latest && \
-          docker run -d  -p 3000:3000 ghcr.io/peakaltitudestudio/pas-website-ghrc"
+          ec2-user@18.144.54.243 <<EOF
+          # Kill the Docker container if it exists, without failing if it doesn't
+          if docker ps -a | grep -q your-docker-image-name; then
+            docker kill your-docker-image-name || true
+          fi
+          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
+          docker pull ghcr.io/peakaltitudestudio/pas-website-ghrc:latest
+          docker run -d -p 3000:3000 ghcr.io/peakaltitudestudio/pas-website-ghrc
+          EOF
+
+
+
+
